### ISSUE TITLE
Any function to reset game or clear played history in board elements?

### ISSUE THREAD

**Issue by yangboz** [aprescott/tenuki#36]
Any function to reset game or clear played history in board elements?
Thanks.

**Comment by aprescott** [comment]
There's currently no reset function, but in the short term you should be able to work around it with `game._moves = []; game.render()`. I appreciate that's a very hacky thing to put in your code, so I'll definitely be adding `reset` into the next release.

**Comment by yangboz** [comment]
I am using the  following workaround:
"
while (boardElement.firstChild) {
              boardElement.removeChild(boardElement.firstChild);
          }
"
