### ISSUE TITLE
Resigning a game

### ISSUE THREAD

**Issue by vlinder** [aprescott/tenuki#41]
There is no way to resign a game that I can find.

Is this intentionally left out for the implementor to add?

**Comment by aprescott** [comment]
This is indeed not currently part of the functionality of a tenuki game instance. Someone handling resignations would need to track that outside of the tenuki logic.

I'm not necessarily opposed to handling it within tenuki, but I don't think the state of a game instance inherently changes after resignation. That makes me think it's simpler to leave the meaning of "resign a game" up to an implementor (e.g., by blocking incoming moves).

**Comment by vlinder** [comment]
Thanks for the answer. :)
