### ISSUE TITLE
No Releases Available

### ISSUE THREAD

**Issue by milescrawford** [aprescott/tenuki#45]
The github readme says you can download files from the `latest releases` page, but there are no releases there.

**Comment by aprescott** [comment]
You can download them from [the Tags section](https://github.com/aprescott/tenuki/tags) of the releases page.

If memory serves, the repo predates the current GitHub UI, where the former made it a little clearer that tags were available.

**Comment by milescrawford** [comment]
Oh, but the tags just provide source code, right, not the built files ready
for use?

**Comment by aprescott** [comment]
Ah, yes, it does assume NPM or build from source as the two options. That's probably too onerous at this point, given the likely drift against the surrounding environment. I will rationalize things a little. If you need a non-NPM workaround you could pull from the same files that are produced for the live examples, through the [`gh-pages` branch](https://github.com/aprescott/tenuki/tree/gh-pages/build). Apologies for the confusion.

**Comment by milescrawford** [comment]
No problem, thanks for clarifying.

**Comment by aprescott** [comment]
v0.3.1 and its built files should now be available as a release with pre-built files available matching those used in the `gh-pages` branch: https://github.com/aprescott/tenuki/releases/tag/v0.3.1

Thanks for mentioning this and apologies again for the confusion and friction. Feel free to mention if there's anything that's amiss.
